from typing import Tuple

SUPPORTED_SCOPES: Tuple[str] = (
    "analytics:read:extensions",
    "analytics:read:games",
    "bits:read",
    "channel:edit:commercial",
    "channel:manage:broadcast",
    "channel:manage:poll",
    "channel:manage:predictions",
    "channel:manage:schedule",
    "channel:manage:videos",
    "channel:read:editors",
    "channel:read:goals",
    "channel:read:hype_train",
    "channel:read:polls",
    "channel:read:predictions",
    "channel:read:redemptions",
    "channel:read:stream_key",
    "channel:read:subscriptions",
    "clips:edit",
    "moderation:read",
    "moderator:manage:banned_users",
    "moderater:read:blocked_terms",
    "moderator:manage:automod",
    "moderator:read:automod_settings",
    "moderator:manage:automod_settings",
    "moderator:read:chage_settings",
    "moderator:manage:chat_settings",
    "user:edit:follows",
    "user:manage:blocked_users",
    "user:blocked_users",
    "user:read:broadcast",
    "user:read:email",
    "user:read:follows",
    "user:read:subscriptions"
)

APIv5_SCOPES: Tuple[str] = (
    "channel_subscriptions",
    "channel_commercial",
    "channel_editor",
    "user_follow",
    "s_edit",
    "channel_read",
    "user_read",
    "user_blocks_read",
    "user_blocks_edit",
    "channel:moderate",
    "chat:edit",
    "chat:read",
    "whisper:read",
    "whispers:edit"
)

